name: Build and Publish Docker Image

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == *"-rc"* ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "environment=production" >> $GITHUB_OUTPUT
          fi

      - name: Extract Tag Name
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_NAME=${IMAGE_NAME,,} # to lowercase
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

          docker build --build-arg NEXT_PUBLIC_BACKEND="https://image.xcoptech.net" -t ${IMAGE_NAME}:${TAG_NAME} .
          docker tag ${IMAGE_NAME}:${TAG_NAME} ${IMAGE_NAME}:latest

      - name: Push Docker Image to GHCR
        run: |
          docker push ${IMAGE_NAME}:${TAG_NAME}
          docker push ${IMAGE_NAME}:latest

      - name: Verify Docker Image
        run: docker images | grep "${IMAGE_NAME}"
